(() => {
  const en = {"Tout commence ici.": "It all starts here.", "Un fichier HTML. Un manifeste. Votre widget.": "One HTML file. One manifest. Your widget.", "Tester l’extension": "Test extension", "Ça fonctionne ✓": "It works ✓", "Focus · 25 min": "Focus · 25 min", "Pause · 5 min": "Break · 5 min", "Temps restant": "Time remaining", "Démarrer": "Start", "Réinitialiser": "Reset", "Prêt pour une session.": "Ready for a session.", "Le minuteur se réinitialise au rechargement.": "The timer resets when you reload.", "Recommencer": "Restart", "Mettre en pause": "Pause", "Session en pause.": "Session paused.", "Une chose à la fois.": "One thing at a time.", "Prenez une respiration.": "Take a breath.", "Session terminée. Place à la pause !": "Session complete. Time for a break!", "Pause terminée. Prêt à repartir ?": "Break complete. Ready to start again?", "Une tâche à accomplir…": "A task to complete…", "Nouvelle tâche": "New task", "Ajouter la tâche": "Add task", "Votre liste est vide.": "Your list is empty.", "Effacer les terminées": "Clear completed", "Liste temporaire : les tâches disparaissent au rechargement.": "Temporary list: tasks disappear when you reload.", "removeTask": "Delete: {text}", "completed": "{done} / {count} completed", "Calendrier": "Calendar", "Mois précédent": "Previous month", "Mois suivant": "Next month", "Calendrier du mois": "Monthly calendar", "Date locale de votre navigateur": "Local date in your browser", "Aujourd’hui": "Today", "Calculatrice": "Calculator", "Expression à calculer": "Expression to calculate", "Entrée pour calculer · Échap pour effacer": "Enter to calculate · Escape to clear", "Effacer le dernier caractère": "Delete last character", "Diviser": "Divide", "Multiplier": "Multiply", "Soustraire": "Subtract", "Calculer": "Calculate", "Additionner": "Add", "Expression invalide": "Invalid expression", "Parenthèse manquante": "Missing closing bracket", "Nombre attendu": "Number expected", "Division par zéro": "Division by zero", "Résultat hors limites": "Result out of range"}, fr = {"removeTask": "Supprimer : {text}", "completed": "{done} / {count} terminées"};
  let lang = navigator.language?.toLowerCase().startsWith('fr') ? 'fr' : 'en';
  const t = (key,params={}) => ((lang==='en'?en[key]:fr[key]) ?? key).replace(/\{(\w+)\}/g,(_,name)=>String(params[name]??''));
  function apply() {
    document.documentElement.lang=lang;
    document.querySelectorAll('[data-i18n]').forEach(node=>node.textContent=t(node.dataset.i18n));
    document.querySelectorAll('[data-i18n-attrs]').forEach(node=>Object.entries(JSON.parse(node.dataset.i18nAttrs)).forEach(([attribute,key])=>node.setAttribute(attribute,t(key))));
  }
  document.addEventListener('dashdock:language',event=>{if(['en','fr'].includes(event.detail?.lang)){lang=event.detail.lang;apply();}});
  window.WidgetI18n={t,lang:()=>lang,apply};apply();
})();
