(() => {
  const $ = id => document.getElementById(id);
  const text = {
    fr:{provider:'Fournisseur',model:'Modèle',models:'Modèles',reset:'Effacer',send:'Envoyer',prompt:'Votre message…',empty:'Une question, une idée, un coup de main ? Écrivez votre premier message.',welcome:'Comment puis-je vous aider ?',newChat:'Nouvelle conversation',prompt:'Écrivez votre message…',hint:'Historique de session. OpenRouter : clé côté serveur ; Ollama / LM Studio : serveur local actif. Les messages sont transmis au fournisseur choisi.',busy:'Réponse en cours…',loaded:'Modèles disponibles chargés.',saved:'Choix enregistré.',missing:'Configurez DASHDOCK_OPENROUTER_KEY côté serveur.',unreachable:'Fournisseur inaccessible. Vérifiez son serveur, son URL et le modèle.',auth:'Authentification refusée par le fournisseur.',rate:'Limite du fournisseur atteinte. Réessayez plus tard.',limit:'Conversation trop longue. Effacez-la pour recommencer.',failed:'La requête a échoué.',you:'Vous',assistant:'Assistant',bridge:'Ouvrez cet assistant depuis DashDock.',tooBusy:'Deux requêtes IA sont déjà en cours. Réessayez.',notconfigured:' (non configuré)',custom:'Saisir un identifiant…',modelId:'Identifiant du modèle',noModels:'Aucun modèle disponible chez ce fournisseur.'},
    en:{provider:'Provider',model:'Model',models:'Models',reset:'Clear',send:'Send',prompt:'Your message…',empty:'A question, an idea, a helping hand? Write your first message.',welcome:'How can I help?',newChat:'New conversation',prompt:'Write your message…',hint:'Session history. OpenRouter: server-side key; Ollama / LM Studio: local server running. Messages are sent to the selected provider.',busy:'Generating a reply…',loaded:'Available models loaded.',saved:'Selection saved.',missing:'Configure DASHDOCK_OPENROUTER_KEY on the server.',unreachable:'Provider unavailable. Check its server, URL and model.',auth:'Provider authentication failed.',rate:'Provider rate limit reached. Try again later.',limit:'Conversation too long. Clear it to start again.',failed:'The request failed.',you:'You',assistant:'Assistant',bridge:'Open this assistant inside DashDock.',tooBusy:'Two AI requests are already running. Try again.',notconfigured:' (not configured)',custom:'Enter a model ID…',modelId:'Model ID',noModels:'No models available from this provider.'}
  };
  let lang='fr', providers=[], messages=[], busy=false, initialized=false, counter=0, statusKey='', availableModels=[];
  const pending=new Map();
  const t=key=>text[lang][key]||text[lang].failed;
  function status(key){statusKey=key;$('status').textContent=key?t(key):'';$('status').dataset.state=key==='busy'?'busy':key==='saved'||key==='loaded'?'success':'idle';}
  function request(method,params={}) {return new Promise((resolve,reject)=>{if(parent===window){reject(new Error('bridge'));return;}const requestId=`assistant-${++counter}`;const timer=setTimeout(()=>{pending.delete(requestId);reject(new Error('provider_unreachable'));},100000);pending.set(requestId,{resolve,reject,timer});parent.postMessage({type:'dashdock:request',requestId,method,params},'*');});}
  function failure(error){const raw=String(error?.message||error);const keys={openrouter_not_configured:'missing',provider_unreachable:'unreachable',provider_authentication_failed:'auth',provider_rate_limited:'rate',ai_busy:'tooBusy',invalid_chat_request:'limit',bridge:'bridge'};status(Object.keys(keys).find(key=>raw.includes(key)) ? keys[Object.keys(keys).find(key=>raw.includes(key))] : 'failed');}
  function render(){document.documentElement.lang=lang;document.title=lang==='fr'?'Assistant IA':'AI Assistant';for(const [id,key]of [['connect','models'],['empty-title','welcome'],['empty-description','empty'],['hint','hint']])$(id).textContent=t(key);$('reset').setAttribute('aria-label',t('newChat'));$('reset').setAttribute('title',t('newChat'));$('send').setAttribute('aria-label',t('send'));$('send').setAttribute('title',t('send'));$('prompt').placeholder=t('prompt');$('prompt').setAttribute('aria-label',t('prompt'));$('provider').setAttribute('aria-label',t('provider'));$('model').setAttribute('aria-label',t('model'));$('custom-model-label').textContent=t('modelId');$('custom-model').setAttribute('aria-label',t('modelId'));setModel(currentModel());$('provider-label').textContent=t('provider');$('model-label').textContent=t('model');const current=$('provider').value;$('provider').replaceChildren(...providers.map(p=>{const el=document.createElement('option');el.value=p.id;el.textContent=p.name+(p.configured?'':t('notconfigured'));return el;}));if(providers.some(p=>p.id===current))$('provider').value=current;status(statusKey);for(const el of document.querySelectorAll('.message strong'))el.textContent=t(el.parentElement.dataset.role==='user'?'you':'assistant');}
  function currentModel(){return $('model').value==='__custom__' ? $('custom-model').value.trim() : $('model').value;}
  function setModel(value){
    value=typeof value==='string'?value:'';
    const select=$('model');select.replaceChildren();
    const choices=[...availableModels];
    if(value && !choices.some(m=>m.id===value))choices.unshift({id:value,name:value});
    for(const model of choices){const option=document.createElement('option');option.value=model.id;option.textContent=model.name===model.id?model.id:`${model.name} · ${model.id}`;select.append(option);}
    const manual=document.createElement('option');manual.value='__custom__';manual.textContent=t('custom');select.append(manual);
    select.value=value || '__custom__';$('custom-model').value=value;$('custom-model-field').hidden=select.value!=='__custom__';
  }
  function selection(){$('selection').textContent=[providers.find(p=>p.id===$('provider').value)?.name,currentModel()].filter(Boolean).join(' · ');$('selection').setAttribute('title',$('selection').textContent);}
  function applyConfig(config){if(!config||typeof config!=='object')return;const before=$('provider').value+'|'+currentModel();if(providers.some(p=>p.id===config.provider)){if($('provider').value!==config.provider)availableModels=[];$('provider').value=config.provider;}setModel(typeof config.model==='string'?config.model:providers.find(p=>p.id===$('provider').value)?.default_model||'');if(before!==$('provider').value+'|'+currentModel()){messages=[];$('conversation').replaceChildren($('empty'));$('empty').hidden=false;}selection();}
  async function save(){selection();try{await request('config.save',{provider:$('provider').value,model:currentModel().trim()});if(document.documentElement.dataset.view==='settings')status('saved');}catch(error){failure(error);}}
  function locks(value){busy=value;for(const id of ['send','provider','model','custom-model','connect','reset'])$(id).disabled=value;$('prompt').disabled=value;}
  function add(message){$('empty').hidden=true;const el=document.createElement('div');el.className='message';el.dataset.role=message.role;const name=document.createElement('strong');name.textContent=t(message.role==='user'?'you':'assistant');el.append(name,document.createTextNode(message.content));$('conversation').append(el);$('conversation').scrollTop=$('conversation').scrollHeight;return el;}
  async function init(){if(initialized)return;initialized=true;try{providers=await request('ai.providers');render();setModel(providers.find(p=>p.id===$('provider').value)?.default_model||'');applyConfig(await request('config.get'));}catch(error){initialized=false;failure(error);}}
  window.addEventListener('message',event=>{if(event.source!==parent||!event.data)return;const data=event.data;if(data.type==='dashdock:response'){const call=pending.get(data.requestId);if(!call)return;clearTimeout(call.timer);pending.delete(data.requestId);data.error?call.reject(new Error(typeof data.error==='string'?data.error: data.error.message||data.error.error||'failed')):call.resolve(data.result);}if(data.type==='dashdock:theme'){if(['fr','en'].includes(data.lang)){lang=data.lang;render();}init();}if(data.type==='dashdock:context'||data.type==='dashdock:config')applyConfig(data.config);});
  $('provider').addEventListener('change',()=>{messages=[];$('conversation').replaceChildren($('empty'));$('empty').hidden=false;setModel(providers.find(p=>p.id===$('provider').value)?.default_model||'');availableModels=[];setModel(currentModel());save();status('');});
  $('model').addEventListener('change',()=>{$('custom-model-field').hidden=$('model').value!=='__custom__';if($('model').value==='__custom__'){$('custom-model').focus();return;}messages=[];$('conversation').replaceChildren($('empty'));$('empty').hidden=false;save();});
  $('custom-model').addEventListener('change',()=>{if(currentModel())save();});
  $('connect').addEventListener('click',async()=>{locks(true);status('busy');try{const result=await request('ai.models',{provider:$('provider').value});availableModels=result.models.filter(model=>typeof model.id==='string' && model.id);setModel(currentModel());status(availableModels.length?'loaded':'noModels');}catch(error){failure(error);}finally{locks(false);}});
  $('reset').addEventListener('click',()=>{messages=[];$('conversation').replaceChildren($('empty'));$('empty').hidden=false;status('');});
  $('form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const content=$('prompt').value.trim(),model=currentModel().trim();if(!content||!model)return;const next=[...messages,{role:'user',content}];if(next.length>20||next.reduce((n,m)=>n+new TextEncoder().encode(m.content).length,0)>64000||new TextEncoder().encode(content).length>16000){status('limit');return;}const userBubble=add(next.at(-1));$('prompt').value='';locks(true);status('busy');try{await save();const result=await request('ai.chat',{provider:$('provider').value,model,messages:next});const reply={role:'assistant',content:result.content};messages=[...next,reply];add(reply);$('prompt').value='';status('');}catch(error){userBubble.remove();$('empty').hidden=messages.length>0;$('prompt').value=content;failure(error);}finally{locks(false);$('prompt').focus();}});
  $('prompt').addEventListener('keydown',event=>{if(event.key==='Enter' && !event.shiftKey && !event.isComposing){event.preventDefault();if(!busy)$('form').requestSubmit();}});
  render();parent.postMessage({type:'dashdock:ready',settings:true},'*');
})();
