(() => {
  const $=id=>document.getElementById(id);let ready=false,saving=false,pending=null,timer=null,draft=UnitConverter.normalize({}),dirty=false;
  function units(){for(const id of ['from','to']){$(id).replaceChildren();for(const unit of Object.keys(UnitConverter.groups[draft.category].units))$(id).append(new Option(unit,unit));$(id).value=draft[id];}}
  function result(){const number=UnitConverter.parse(draft.value),converted=UnitConverter.convert(number,draft.category,draft.from,draft.to);$('result').textContent=converted===null?'—':UnitConverter.format(converted,dash.lang==='en'?'en-GB':'fr-FR')+' '+draft.to;$('hint').textContent=converted===null?dash.t('Saisissez un nombre valide (virgule ou point).','Enter a valid number (comma or decimal point).'):draft.category==='storage'?dash.t('kB = 1 000 octets · KiB = 1 024 octets','kB = 1,000 bytes · KiB = 1,024 bytes'):draft.category==='temperature'?dash.t('Le zéro absolu est −273,15 °C.','Absolute zero is −273.15 °C.'):dash.t('Conversion instantanée, sans connexion.','Instant conversion, works offline.');}
  function render(sync=false){$('category-label').textContent=dash.t('Convertir','Convert');$('from-label').textContent=dash.t('De','From');$('to-label').textContent=dash.t('Vers','To');$('value-label').textContent=dash.t('Valeur','Value');$('swap').setAttribute('aria-label',dash.t('Inverser les unités','Swap units'));$('retry').textContent=dash.t('Réessayer','Retry');$('category').replaceChildren();for(const [id,group] of Object.entries(UnitConverter.groups))$('category').append(new Option(dash.t(group.fr,group.en),id));$('category').value=draft.category;units();if(sync)$('value').value=draft.value;for(const id of ['category','from','to','value','swap'])$(id).disabled=!ready;result();}
  async function flush(){if(saving||!pending)return;saving=true;const next=pending;pending=null;try{await dash.save(next);if(!pending&&!timer){dirty=false;$('error').textContent='';$('retry').hidden=true;}}catch(_){$('error').textContent=dash.t('Préférences non sauvegardées. Votre conversion reste disponible. Réessayez.','Preferences were not saved. Your conversion remains available. Retry.');$('retry').hidden=false;pending=pending||next;}finally{saving=false;if(pending&&pending!==next)flush();}}
  function queue(){dirty=true;clearTimeout(timer);timer=setTimeout(()=>{timer=null;pending={...draft};flush();},350);result();}
  $('converter').onsubmit=event=>event.preventDefault();$('value').oninput=()=>{draft.value=$('value').value;queue();};$('category').onchange=()=>{draft=UnitConverter.normalize({category:$('category').value,value:draft.value});units();queue();};for(const id of ['from','to'])$(id).onchange=()=>{draft[id]=$(id).value;queue();};$('swap').onclick=()=>{[draft.from,draft.to]=[draft.to,draft.from];units();queue();};
  async function initialize(){$('retry').hidden=true;try{await dash.start();ready=true;if(!dirty)draft=UnitConverter.normalize(dash.config);$('error').textContent='';render(true);}catch(_){$('error').textContent=dash.t('Impossible de charger les préférences. Réessayez avant de les modifier.','Could not load preferences. Retry before editing.');$('retry').hidden=false;}}
  $('retry').onclick=()=>ready?flush():initialize();addEventListener('dashdock:language',()=>render());addEventListener('dashdock:context',()=>{if(!dirty&&!saving){draft=UnitConverter.normalize(dash.config);render(true);}});render(true);initialize();
})();
