(() => {
  const $=id=>document.getElementById(id),view=new URLSearchParams(location.search).get('view')||'preview';document.documentElement.dataset.view=view;
  let ready=false,busy=false,dirty=false;
  const zones=['Europe/Brussels','Europe/Paris','Europe/London','Europe/Berlin','Europe/Madrid','Europe/Rome','Europe/Zurich','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','America/Toronto','America/Sao_Paulo','Asia/Tokyo','Asia/Shanghai','Asia/Kolkata','Asia/Dubai','Asia/Singapore','Australia/Sydney','Pacific/Auckland','UTC'];
  const available=typeof Intl.supportedValuesOf==='function'?Intl.supportedValuesOf('timeZone'):zones;
  const datalist=document.createElement('datalist');datalist.id='zones';for(const zone of available){const option=document.createElement('option');option.value=zone;datalist.append(option);}document.body.append(datalist);
  for(let i=0;i<4;i++){const row=document.createElement('div');row.className='field';const label=document.createElement('label');label.id='label-'+i;label.htmlFor='city-'+i;const city=document.createElement('input');city.id='city-'+i;city.maxLength=60;const zoneLabel=document.createElement('label');zoneLabel.id='zone-label-'+i;zoneLabel.htmlFor='zone-'+i;const zone=document.createElement('input');zone.id='zone-'+i;zone.maxLength=100;zone.setAttribute('list','zones');city.oninput=zone.oninput=()=>dirty=true;row.append(label,city,zoneLabel,zone);$('fields').append(row);}
  function tick(){const now=new Date(),localZone=Intl.DateTimeFormat().resolvedOptions().timeZone,locale=dash.lang==='en'?'en-GB':'fr-FR';$('clocks').replaceChildren();for(const row of WorldClock.normalize(dash.config.clocks)){const value=WorldClock.clock(now,row.zone,locale,localZone),element=document.createElement('div');element.className='clock';const label=document.createElement('div'),name=document.createElement('strong'),date=document.createElement('span'),time=document.createElement('b');name.textContent=row.label;date.textContent=value.date+(value.offset?` · ${value.offset>0?'+':''}${value.offset} ${dash.t('j','d')}`:'');time.textContent=value.time;label.append(name,date);element.append(label,time);$('clocks').append(element);}$('local').textContent=dash.t('Par rapport à votre heure locale · ','Compared with your local time · ')+localZone;}
  function render(sync=false){tick();$('intro').textContent=dash.t('Le monde, à la même seconde','The world, at the same moment');$('settings-title').textContent=dash.t('Vos horloges','Your clocks');$('help').textContent=dash.t('Jusqu’à quatre villes. Les heures suivent automatiquement l’heure d’été. Laissez une ligne vide pour la retirer.','Up to four cities. Daylight saving changes are automatic. Leave a row empty to remove it.');$('save').textContent=busy?dash.t('Enregistrement…','Saving…'):dash.preview?dash.t('Essayer ces horloges','Try these clocks'):dash.t('Enregistrer','Save');$('retry').textContent=dash.t('Réessayer','Retry');const rows=WorldClock.normalize(dash.config.clocks);for(let i=0;i<4;i++){$('label-'+i).textContent=dash.t('Ville ','City ')+(i+1);$('zone-label-'+i).textContent=dash.t('Fuseau IANA','IANA time zone');for(const id of ['city-'+i,'zone-'+i])$(id).disabled=!ready||busy;if(sync&&!dirty){$('city-'+i).value=rows[i]?.label||'';$('zone-'+i).value=rows[i]?.zone||'';}}$('save').disabled=!ready||busy;}
  $('form').onsubmit=async event=>{event.preventDefault();if(!ready||busy)return;const clocks=[];for(let i=0;i<4;i++){const label=$('city-'+i).value.trim(),zone=$('zone-'+i).value.trim();if(!label&&!zone)continue;if(!label||label.length>60||!WorldClock.validZone(zone)){$('error').textContent=dash.t('Vérifiez le nom et le fuseau de chaque ville.','Check the name and time zone of each city.');return;}clocks.push({label,zone});}if(!clocks.length){$('error').textContent=dash.t('Ajoutez au moins une ville.','Add at least one city.');return;}busy=true;$('error').textContent='';render();try{await dash.save({clocks});dirty=false;}catch(_){$('error').textContent=dash.t('Enregistrement impossible. Votre saisie est conservée.','Could not save. Your draft has been kept.');}finally{busy=false;render(true);}};
  async function initialize(){$('retry').hidden=true;try{await dash.start();ready=true;$('error').textContent='';render(true);}catch(_){$('error').textContent=dash.t('Impossible de charger vos horloges. Réessayez avant de les modifier.','Could not load your clocks. Retry before editing.');$('retry').hidden=false;}}
  $('retry').onclick=initialize;addEventListener('dashdock:language',()=>render());addEventListener('dashdock:context',()=>render(true));render();initialize();setInterval(tick,1000);
})();
