(() => {
 const $=id=>document.getElementById(id),t=(fr,en)=>dash.t(fr,en),settings=new URLSearchParams(location.search).get('view')==='settings';if(settings)document.body.classList.add('settings-view');
 let data=null,ready=false,busy=false,revision=0,timer;
 function el(tag,text,cls){const n=document.createElement(tag);n.textContent=String(text??'');if(cls)n.className=cls;return n;}
 function showError(code){const messages={provider_not_configured:t('Configurez Tailscale dans les réglages.','Set up Tailscale in settings.'),provider_auth_failed:t('Accès refusé : vérifiez la clé ou les droits OAuth.','Access denied: check the key or OAuth scopes.'),provider_wrong_key_type:t('Utilisez un jeton API, pas une clé d’inscription tskey-auth.','Use an API access token, not a tskey-auth enrollment key.'),provider_rate_limited:t('Limite API atteinte. Réessayez dans une minute.','API rate limit reached. Retry in a minute.'),provider_invalid_response:t('Réponse Tailscale non reconnue.','Unrecognized Tailscale response.'),provider_response_too_large:t('Tailnet trop volumineux pour ce widget.','Tailnet too large for this widget.'),provider_invalid_tailnet:t('Identifiant tailnet invalide.','Invalid tailnet identifier.'),provider_unavailable:t('API Tailscale inaccessible.','Tailscale API unavailable.')};$('error').textContent=messages[code]||t('Chargement impossible. Réessayez.','Unable to load. Please retry.');}
 function renderList(){const list=$('devices');list.replaceChildren();if(!data){$('matches').textContent='';return;}const query=$('search').value.toLocaleLowerCase().trim();const filtered=data.devices.filter(d=>(d.name+' '+d.dns+' '+d.os+' '+d.addresses.join(' ')).toLocaleLowerCase().includes(query));
  $('matches').textContent=filtered.length+t(' appareil(s) · aperçu de 20',' device(s) · preview of 20');
  for(const d of filtered.slice(0,20)){const row=el('div','','row'),detail=el('div');detail.append(el('strong',d.name),el('small',d.os+' · '+(d.addresses[0]||t('Sans adresse','No address'))));
   const last=Date.parse(d.last_seen);let status=!d.authorized?t('À approuver','Needs approval'):Number.isFinite(last)?t('Vu à ','Seen at ')+new Date(last).toLocaleString(dash.lang==='en'?'en-GB':'fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):t('Activité inconnue','Activity unknown');
   const expiry=Date.parse(d.expires);if(!d.key_expiry_disabled&&Number.isFinite(expiry)&&expiry<=Date.now())status=t('Clé expirée','Key expired');
   const tag=el('span',status,'tag');if(!d.authorized)tag.className+=' pending';row.append(detail,tag);list.append(row);}
  if(!filtered.length)list.append(el('p',data.devices.length?t('Aucun appareil correspondant.','No matching devices.'):t('Aucun appareil dans ce tailnet.','No devices in this tailnet.'),'muted'));
 }
 function render(){
  $('heading').textContent=t('Votre réseau privé','Your private network');$('refresh').textContent=t('Actualiser','Refresh');$('connect').textContent=t('Vérifier la connexion','Check connection');$('save').textContent=t('Enregistrer le filtre','Save filter');$('filter-label').textContent=t('Filtre par nom, système ou adresse','Filter by name, OS or address');$('search').placeholder=t('Rechercher un appareil…','Search devices…');$('search').setAttribute('aria-label',t('Rechercher un appareil','Search devices'));
  $('demo').hidden=!dash.preview;$('demo').textContent=t('Aperçu · données fictives','Preview · demo data');$('help').textContent=t('Clés conservées sur le serveur. OAuth en lecture seule conseillé.','Keys stay on the server. Read-only OAuth recommended.');$('scope').textContent=t('Permissions OAuth : Devices → Core → Read. Aucun appareil ni règle réseau ne peut être modifié.','OAuth scope: Devices → Core → Read. Devices and network rules cannot be modified.');$('notice').textContent=t('La dernière activité est un relevé API, pas un test de connexion en direct.','Last activity is an API observation, not a live connectivity test.');
  for(const id of ['refresh','connect','save','filter'])$(id).disabled=!ready||busy;
  $('search').hidden=!data;const root=$('content');root.replaceChildren();$('updated').textContent='';
  if(data){const metrics=el('div','','metrics');for(const [value,fr,en] of [[data.total,'Appareils','Devices'],[data.authorized,'Autorisés','Approved'],[data.pending,'À approuver','Pending']]){const m=el('div','','metric');m.append(el('strong',value),el('span',t(fr,en)));metrics.append(m);}root.append(metrics);$('updated').textContent=dash.preview?t('Exemple sans connexion API','Example without API connection'):t('Relevé à ','Checked at ')+new Date(data.checked_at*1000).toLocaleTimeString()+t(' · actualisation 60 s',' · refresh every 60 s');}
  else{const box=el('div','','empty');box.append(el('strong',busy?t('Connexion…','Connecting…'):t('Connectez votre tailnet','Connect your tailnet')),el('p',t('Ouvrez les réglages pour connecter votre réseau Tailscale.','Open settings to connect your Tailscale network.')));root.append(box);}renderList();
 }
 function setup(){const root=$('setup');root.replaceChildren();root.append(el('h3',t('Configuration serveur (.env)','Server configuration (.env)')));for(const key of ['DASHDOCK_TAILSCALE_CLIENT_ID','DASHDOCK_TAILSCALE_CLIENT_SECRET','DASHDOCK_TAILSCALE_TAILNET'])root.append(el('code',key+'=…'));root.append(el('p',t('Tailnet : « - » sélectionne le réseau lié au jeton. Alternative OAuth : DASHDOCK_TAILSCALE_API_KEY (tskey-api). Recréez le conteneur après modification du .env.','Tailnet: “-” selects the token’s network. OAuth alternative: DASHDOCK_TAILSCALE_API_KEY (tskey-api). Recreate the container after editing .env.'),'muted'));}
 async function load(){if(!ready)return;const at=++revision;busy=true;$('error').textContent='';render();try{let next;if(dash.preview){next={total:3,authorized:2,pending:1,devices:[{name:'homelab',dns:'homelab.example.ts.net',os:'linux',addresses:['100.64.0.10'],authorized:true,last_seen:new Date().toISOString(),expires:'',key_expiry_disabled:true},{name:'laptop',dns:'laptop.example.ts.net',os:'windows',addresses:['100.64.0.20'],authorized:true,last_seen:new Date(Date.now()-3600000).toISOString(),expires:'',key_expiry_disabled:true},{name:'phone',dns:'',os:'android',addresses:['100.64.0.30'],authorized:false,last_seen:'',expires:'',key_expiry_disabled:false}]};}else next=await dash.request('tailscale.devices');if(at===revision)data=next;}catch(e){if(at===revision){data=null;showError(e.message);}}finally{if(at===revision){busy=false;render();}}}
 $('search').addEventListener('input',renderList);$('refresh').addEventListener('click',load);$('connect').addEventListener('click',load);$('save').addEventListener('click',async()=>{busy=true;render();try{await dash.save({...dash.config,filter:$('filter').value.trim().slice(0,100)});$('error').textContent=t('Filtre enregistré.','Filter saved.');}catch(e){showError(e.message);}finally{busy=false;render();}});
 addEventListener('dashdock:language',()=>{setup();render();});addEventListener('dashdock:context',()=>{if(ready){$('filter').value=dash.config.filter||'';$('search').value=dash.config.filter||'';renderList();}});
 async function start(){try{await dash.start();ready=true;$('filter').value=dash.config.filter||'';$('search').value=dash.config.filter||'';await load();timer=setInterval(()=>{if(!busy&&!document.hidden&&!settings)load();},60000);}catch(e){showError(e.message);}}
 addEventListener('pagehide',()=>clearInterval(timer));setup();render();start();
})();