(() => {
  let sequence=0,revision=0;const pending=new Map();
  function validate(config){const walk=(value,depth)=>{if(depth>6)throw Error('Configuration too deep');if(typeof value==='string'){if(new TextEncoder().encode(value).length>2000)throw Error('Text too long');}else if(typeof value==='number'){if(!Number.isFinite(value))throw Error('Invalid number');}else if(value&&typeof value==='object'){if(Array.isArray(value)&&value.length>100)throw Error('Too many items');for(const [key,item] of Object.entries(value)){if(new TextEncoder().encode(key).length>2000)throw Error('Key too long');walk(item,depth+1);}}else if(value!==null&&typeof value!=='boolean')throw Error('Invalid configuration');};if(!config||typeof config!=='object'||Array.isArray(config))throw Error('Invalid configuration');walk(config,0);if(new TextEncoder().encode(JSON.stringify(config)).length>8192)throw Error('Configuration too large');}
  window.dash={lang:'fr',preview:new URLSearchParams(location.search).get('view')==='preview',config:{},t(fr,en){return this.lang==='en'?en:fr;},
    request(method,params={}){const requestId=`local-${Date.now()}-${++sequence}`;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(requestId);reject(Error('Service timeout'));},30000);pending.set(requestId,{resolve,reject,timer});parent.postMessage({type:'dashdock:request',requestId,method,params},'*');});},
    async save(config){validate(config);const at=revision;if(!this.preview)await this.request('config.save',{config});if(at===revision)this.config=config;},
    async start(){parent.postMessage({type:'dashdock:ready',settings:true},'*');const at=revision,result=await this.request('config.get'),config=result?.config||result;validate(config);if(at===revision)this.config=config;return this.config;}
  };
  addEventListener('message',event=>{if(event.source!==parent||!event.data||typeof event.data!=='object')return;const message=event.data;
    if(message.type==='dashdock:response'){const task=pending.get(message.requestId);if(!task)return;clearTimeout(task.timer);pending.delete(message.requestId);if(message.error)task.reject(Error(typeof message.error==='string'?message.error:'request_failed'));else task.resolve(message.result);}
    else if(message.type==='dashdock:context'||message.type==='dashdock:config'){if(message.type==='dashdock:context')dash.preview=message.preview===true;if(message.config){try{validate(message.config);dash.config=message.config;revision++;}catch(_){return;}}dispatchEvent(new Event('dashdock:context'));}
    else if(message.type==='dashdock:theme'){const root=document.documentElement;if(['fr','en'].includes(message.lang)){dash.lang=message.lang;root.lang=message.lang;}if(['light','dark'].includes(message.theme))root.dataset.theme=message.theme;const fonts={system:'system-ui,sans-serif',humanist:'"Trebuchet MS","Segoe UI",sans-serif',mono:'"Cascadia Code",Consolas,monospace'};if(Object.hasOwn(fonts,message.font))root.style.setProperty('--font',fonts[message.font]);if(message.colors)for(const key of ['bg','text','muted','surface','border'])if(/^#[a-f0-9]{6}$/i.test(message.colors[key]||''))root.style.setProperty('--'+key,message.colors[key]);if(/^#[a-f0-9]{6}$/i.test(message.accent||''))root.style.setProperty('--accent',message.accent);dispatchEvent(new Event('dashdock:language'));}
  });
})();
